import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ezone.work/")
    page.get_by_role("link", name="登录").click()
    page.get_by_placeholder("用户名/邮箱/手机号").click()
    page.get_by_placeholder("用户名/邮箱/手机号").fill("pidanxiaozi")
    page.get_by_placeholder("用户名/邮箱/手机号").press("Tab")
    page.get_by_placeholder("密码").fill("危局红1")
    page.get_by_role("button", name="登 录").click()
    page.get_by_placeholder("密码").click()
    page.get_by_placeholder("密码").fill("weijuhong581")
    page.get_by_placeholder("密码").press("Enter")
    page.get_by_role("button", name="登 录").click()
    page.get_by_role("alert").get_by_text("pidanxiaozi").click()
    expect(page.get_by_text("P", exact=True).first).to_be_visible()
    expect(page.get_by_text("pidanxiaozi").first).to_be_visible()
    expect(page.get_by_role("banner")).to_contain_text("P")
    expect(page.get_by_text("P", exact=True).first).to_be_visible()
    page.get_by_role("link", name="进入工作台").click()
    page.locator("#main").click()
    page.locator("#main").click()
    page.get_by_role("link", name="我的任务").click()
    page.get_by_role("link", name="calendar 工时日历").click()
    page.get_by_role("link", name="流程审批").first.click()
    page.locator("#rc_select_8").click()
    page.locator("#main").click()
    page.get_by_role("link", name="项目集").click()
    page.get_by_role("button", name="新 建").click()
    page.get_by_placeholder("-32个字符").click()
    page.locator(".ant-drawer-mask").click()
    page.get_by_placeholder("请输入项目集名称").click()
    page.get_by_role("button", name="新 建").click()
    page.get_by_role("button", name="取 消").click()
    page.locator("#main > div > div > .customScrollBar").click()
    page.get_by_role("tab", name="我是管理员").click()
    page.locator("div").filter(has_text=re.compile(r"^新 建$")).click()
    page.get_by_role("tab", name="我的收藏").click()
    page.get_by_role("tab", name="我是管理员").click()
    page.get_by_role("tab", name="我的全部").click()
    page.get_by_text("暂无数据").click()
    page.locator("#main > div > div > .customScrollBar").click()
    page.get_by_role("link", name="setting 企业设置").click()
    page.locator("#main").click()
    page.get_by_role("link", name="项目集").click()
    page.get_by_role("button", name="新 建").click()
    page.get_by_placeholder("-32个字符").click()
    page.get_by_role("button", name="确 定").click()
    page.get_by_role("cell", name="star setting").locator("span").nth(2).click()
    page.get_by_label("right", exact=True).locator("svg").click()
    page.locator("#sideBarContainer").get_by_role("link", name="项目集", exact=True).click()
    expect(page.get_by_role("cell", name="star setting").locator("span").nth(2)).to_be_visible()
    expect(page.get_by_placeholder("请输入项目集名称")).to_be_empty();
    expect(page.get_by_placeholder("请输入项目集名称")).to_be_empty();
    page.get_by_role("cell", name="star setting").locator("span").nth(2).click(button="right")
    page.get_by_role("cell", name="star setting").locator("span").nth(2).click()
    page.get_by_label("right", exact=True).locator("svg").click()
    page.get_by_role("link", name="运维操作").click()
    page.get_by_role("link", name="基本信息").click()
    page.locator("._mask_1af43_63").click()
    page.locator("._mask_1af43_63").click()
    page.get_by_text("为保证您的使用体验，建议您使用推荐浏览器。 Xpidanxiaozipidanxiaozi2025-04-10 14:50:08Ppidanxiaozi").press("ControlOrMeta+a")
    page.locator("._mask_1af43_63").click()
    page.locator("._mask_1af43_63").click()
    page.locator("._mask_1af43_63").click()
    page.locator("#sideBarContainer").get_by_role("link", name="项目集", exact=True).click()
    page.get_by_role("button", name="新 建").click()
    page.get_by_placeholder("-32个字符").fill("自动化创建项目集")
    page.get_by_placeholder("-32个字符").click()
    page.get_by_role("button", name="确 定").click()
    page.get_by_placeholder("请输入项目集名称").click()
    page.get_by_placeholder("请输入项目集名称").fill("自动化创建项目集")
    page.goto("https://pidanxiaozi.ezone.work/portfolio?search=%E8%87%AA%E5%8A%A8%E5%8C%96%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE%E9%9B%86")
    expect(page.get_by_role("link", name="自动化创建项目集")).to_be_visible()
    expect(page.get_by_role("link", name="自动化创建项目集")).to_be_visible()
    expect(page.locator("tbody")).to_contain_text("自动化创建项目集")
    expect(page.locator("tbody")).to_contain_text("自动化创建项目集")
    page.locator("#main > div > div > .customScrollBar").click()
    page.locator("#main > div > div > .customScrollBar").click()
    page.get_by_role("link", name="项目集", exact=True).click()
    page.get_by_role("link", name="项目管理").click()
    page.get_by_role("link", name="项目列表").click()
    page.get_by_role("link", name="项目集", exact=True).click()
    page.get_by_role("button", name="新 建").click()
    page.get_by_placeholder("开始日期").click()
    page.get_by_title("-04-01").locator("div").click()
    page.get_by_title("-04-06").locator("div").click()
    page.get_by_role("button", name="确 定").click()
    page.get_by_placeholder("-32个字符").click()
    page.locator("div").filter(has_text=re.compile(r"^项目集名称请输入项目集名称项目集周期父项目集请选择父项目集子项目集添加子项目集取 消确 定$")).click()
    page.get_by_placeholder("开始日期").click()
    page.get_by_title("-04-01").locator("div").click()
    page.get_by_title("-04-06").locator("div").click()
    page.locator(".ant-drawer-mask").click()
    page.get_by_role("button", name="新 建").click()
    page.get_by_placeholder("结束日期").click()
    page.locator("div").filter(has_text=re.compile(r"^项目集名称项目集周期父项目集请选择父项目集子项目集添加子项目集取 消确 定$")).click()
    page.get_by_placeholder("开始日期").click()
    page.get_by_title("-04-01").locator("div").click()
    page.locator("div").filter(has_text=re.compile(r"^项目集名称项目集周期父项目集请选择父项目集子项目集添加子项目集取 消确 定$")).click()
    page.locator(".ant-drawer-mask").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
